name: 'analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'batch_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:         
  - "target"
  - "dbt_packages"

# Configuring models
models:
  analytics:
    +materialized: table